@extends('errors.layout')
@section('title', 'Page Not Found')
@section('code', '404')
@section('icon', 'fa-compass')
@section('heading', 'Page Not Found')
@section('message', 'The page you are looking for does not exist or may have been moved.')
