@extends('errors.layout')
@section('title', 'Too Many Requests')
@section('code', '429')
@section('icon', 'fa-gauge-high')
@section('heading', 'Too Many Requests')
@section('message', 'You have sent too many requests. Please wait a moment and try again.')
