<?php

/**
 * Curated Font Awesome 6 solid icons for programs & services (stored as "fa-*").
 */
return [
    ['fa-rocket', 'Rocket'],
    ['fa-lightbulb', 'Lightbulb'],
    ['fa-graduation-cap', 'Graduation'],
    ['fa-chart-line', 'Growth chart'],
    ['fa-chart-pie', 'Analytics'],
    ['fa-users', 'Team'],
    ['fa-user-graduate', 'Student'],
    ['fa-handshake', 'Partnership'],
    ['fa-coins', 'Funding'],
    ['fa-money-bill-wave', 'Money'],
    ['fa-piggy-bank', 'Savings'],
    ['fa-wallet', 'Wallet'],
    ['fa-building', 'Building'],
    ['fa-city', 'City'],
    ['fa-landmark', 'Institution'],
    ['fa-briefcase', 'Business'],
    ['fa-store', 'Store'],
    ['fa-globe', 'Global'],
    ['fa-network-wired', 'Network'],
    ['fa-seedling', 'Seedling'],
    ['fa-leaf', 'Sustainability'],
    ['fa-flask', 'Research'],
    ['fa-microscope', 'Science'],
    ['fa-laptop-code', 'Software'],
    ['fa-code', 'Code'],
    ['fa-mobile-screen', 'Mobile'],
    ['fa-cloud', 'Cloud'],
    ['fa-database', 'Data'],
    ['fa-robot', 'AI / Robotics'],
    ['fa-brain', 'Innovation'],
    ['fa-cogs', 'Operations'],
    ['fa-tools', 'Tools'],
    ['fa-wrench', 'Technical support'],
    ['fa-screwdriver-wrench', 'Mentorship'],
    ['fa-puzzle-piece', 'Problem solving'],
    ['fa-cubes', 'Modules'],
    ['fa-layer-group', 'Programs'],
    ['fa-sitemap', 'Structure'],
    ['fa-project-diagram', 'Strategy'],
    ['fa-bullseye', 'Goals'],
    ['fa-trophy', 'Achievement'],
    ['fa-medal', 'Award'],
    ['fa-award', 'Recognition'],
    ['fa-star', 'Featured'],
    ['fa-certificate', 'Certificate'],
    ['fa-book', 'Learning'],
    ['fa-book-open', 'Knowledge'],
    ['fa-chalkboard-user', 'Training'],
    ['fa-comments', 'Discussion'],
    ['fa-comment-dots', 'Feedback'],
    ['fa-bullhorn', 'Marketing'],
    ['fa-megaphone', 'Promotion'],
    ['fa-envelope', 'Email'],
    ['fa-phone', 'Phone'],
    ['fa-headset', 'Support'],
    ['fa-life-ring', 'Help'],
    ['fa-shield-halved', 'Security'],
    ['fa-lock', 'Protection'],
    ['fa-key', 'Access'],
    ['fa-clipboard-check', 'Checklist'],
    ['fa-list-check', 'Tasks'],
    ['fa-calendar-days', 'Schedule'],
    ['fa-clock', 'Time'],
    ['fa-road', 'Journey'],
    ['fa-map-location-dot', 'Location'],
    ['fa-compass', 'Direction'],
    ['fa-flag', 'Milestone'],
    ['fa-plane', 'Travel'],
    ['fa-truck', 'Logistics'],
    ['fa-industry', 'Manufacturing'],
    ['fa-tractor', 'Agriculture'],
    ['fa-heart-pulse', 'Health'],
    ['fa-stethoscope', 'Healthcare'],
    ['fa-hospital', 'Medical'],
    ['fa-apple-whole', 'Food'],
    ['fa-utensils', 'Hospitality'],
    ['fa-bolt', 'Energy'],
    ['fa-solar-panel', 'Green energy'],
    ['fa-recycle', 'Circular economy'],
    ['fa-scale-balanced', 'Legal'],
    ['fa-balance-scale', 'Legal (legacy)'],
    ['fa-gavel', 'Compliance'],
    ['fa-file-contract', 'Contracts'],
    ['fa-hand-holding-heart', 'Social impact'],
    ['fa-hands-holding-circle', 'Community'],
    ['fa-people-group', 'Community group'],
    ['fa-user-tie', 'Professional'],
    ['fa-infinity', 'Scale'],
    ['fa-paper-plane', 'Launch'],
    ['fa-arrow-trend-up', 'Trending up'],
    ['fa-magnifying-glass-chart', 'Market research'],
];
